// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_vitals.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const getAgentVitalsHistory = `-- name: GetAgentVitalsHistory :many
SELECT id, agent_id, cpu_pct, mem_used_mb, mem_total_mb, system_uptime_secs, agent_uptime_secs, reported_at, received_at,
       agent_version, config_version, is_running, started_at, stopped_at,
       checks_performed, checks_successful, checks_failed,
       failed_report_count, server_connected, cache_capacity, cache_len
FROM agent_vitals
WHERE agent_id = ?
  AND reported_at >= ?
  AND reported_at <= ?
ORDER BY reported_at ASC
`

type GetAgentVitalsHistoryParams struct {
	AgentID      string
	ReportedAt   time.Time
	ReportedAt_2 time.Time
}

type GetAgentVitalsHistoryRow struct {
	ID                string
	AgentID           string
	CpuPct            sql.NullFloat64
	MemUsedMb         sql.NullFloat64
	MemTotalMb        sql.NullFloat64
	SystemUptimeSecs  sql.NullInt64
	AgentUptimeSecs   sql.NullInt64
	ReportedAt        time.Time
	ReceivedAt        time.Time
	AgentVersion      sql.NullString
	ConfigVersion     sql.NullInt64
	IsRunning         sql.NullInt64
	StartedAt         sql.NullTime
	StoppedAt         sql.NullTime
	ChecksPerformed   sql.NullInt64
	ChecksSuccessful  sql.NullInt64
	ChecksFailed      sql.NullInt64
	FailedReportCount sql.NullInt64
	ServerConnected   sql.NullInt64
	CacheCapacity     sql.NullInt64
	CacheLen          sql.NullInt64
}

func (q *Queries) GetAgentVitalsHistory(ctx context.Context, arg GetAgentVitalsHistoryParams) ([]GetAgentVitalsHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentVitalsHistory, arg.AgentID, arg.ReportedAt, arg.ReportedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentVitalsHistoryRow
	for rows.Next() {
		var i GetAgentVitalsHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CpuPct,
			&i.MemUsedMb,
			&i.MemTotalMb,
			&i.SystemUptimeSecs,
			&i.AgentUptimeSecs,
			&i.ReportedAt,
			&i.ReceivedAt,
			&i.AgentVersion,
			&i.ConfigVersion,
			&i.IsRunning,
			&i.StartedAt,
			&i.StoppedAt,
			&i.ChecksPerformed,
			&i.ChecksSuccessful,
			&i.ChecksFailed,
			&i.FailedReportCount,
			&i.ServerConnected,
			&i.CacheCapacity,
			&i.CacheLen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAgentVitals = `-- name: GetLatestAgentVitals :one
SELECT id, agent_id, cpu_pct, mem_used_mb, mem_total_mb, system_uptime_secs, agent_uptime_secs, reported_at, received_at,
       agent_version, config_version, is_running, started_at, stopped_at,
       checks_performed, checks_successful, checks_failed,
       failed_report_count, server_connected, cache_capacity, cache_len
FROM agent_vitals
WHERE agent_id = ?
ORDER BY reported_at DESC
LIMIT 1
`

type GetLatestAgentVitalsRow struct {
	ID                string
	AgentID           string
	CpuPct            sql.NullFloat64
	MemUsedMb         sql.NullFloat64
	MemTotalMb        sql.NullFloat64
	SystemUptimeSecs  sql.NullInt64
	AgentUptimeSecs   sql.NullInt64
	ReportedAt        time.Time
	ReceivedAt        time.Time
	AgentVersion      sql.NullString
	ConfigVersion     sql.NullInt64
	IsRunning         sql.NullInt64
	StartedAt         sql.NullTime
	StoppedAt         sql.NullTime
	ChecksPerformed   sql.NullInt64
	ChecksSuccessful  sql.NullInt64
	ChecksFailed      sql.NullInt64
	FailedReportCount sql.NullInt64
	ServerConnected   sql.NullInt64
	CacheCapacity     sql.NullInt64
	CacheLen          sql.NullInt64
}

func (q *Queries) GetLatestAgentVitals(ctx context.Context, agentID string) (GetLatestAgentVitalsRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentVitals, agentID)
	var i GetLatestAgentVitalsRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CpuPct,
		&i.MemUsedMb,
		&i.MemTotalMb,
		&i.SystemUptimeSecs,
		&i.AgentUptimeSecs,
		&i.ReportedAt,
		&i.ReceivedAt,
		&i.AgentVersion,
		&i.ConfigVersion,
		&i.IsRunning,
		&i.StartedAt,
		&i.StoppedAt,
		&i.ChecksPerformed,
		&i.ChecksSuccessful,
		&i.ChecksFailed,
		&i.FailedReportCount,
		&i.ServerConnected,
		&i.CacheCapacity,
		&i.CacheLen,
	)
	return i, err
}

const insertAgentVitals = `-- name: InsertAgentVitals :exec
INSERT INTO agent_vitals (
    id,
    agent_id,
    cpu_pct,
    mem_used_mb,
    mem_total_mb,
    system_uptime_secs,
    agent_uptime_secs,
    reported_at,
    agent_version,
    config_version,
    is_running,
    started_at,
    stopped_at,
    checks_performed,
    checks_successful,
    checks_failed,
    failed_report_count,
    server_connected,
    cache_capacity,
    cache_len
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentVitalsParams struct {
	ID                string
	AgentID           string
	CpuPct            sql.NullFloat64
	MemUsedMb         sql.NullFloat64
	MemTotalMb        sql.NullFloat64
	SystemUptimeSecs  sql.NullInt64
	AgentUptimeSecs   sql.NullInt64
	ReportedAt        time.Time
	AgentVersion      sql.NullString
	ConfigVersion     sql.NullInt64
	IsRunning         sql.NullInt64
	StartedAt         sql.NullTime
	StoppedAt         sql.NullTime
	ChecksPerformed   sql.NullInt64
	ChecksSuccessful  sql.NullInt64
	ChecksFailed      sql.NullInt64
	FailedReportCount sql.NullInt64
	ServerConnected   sql.NullInt64
	CacheCapacity     sql.NullInt64
	CacheLen          sql.NullInt64
}

func (q *Queries) InsertAgentVitals(ctx context.Context, arg InsertAgentVitalsParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentVitals,
		arg.ID,
		arg.AgentID,
		arg.CpuPct,
		arg.MemUsedMb,
		arg.MemTotalMb,
		arg.SystemUptimeSecs,
		arg.AgentUptimeSecs,
		arg.ReportedAt,
		arg.AgentVersion,
		arg.ConfigVersion,
		arg.IsRunning,
		arg.StartedAt,
		arg.StoppedAt,
		arg.ChecksPerformed,
		arg.ChecksSuccessful,
		arg.ChecksFailed,
		arg.FailedReportCount,
		arg.ServerConnected,
		arg.CacheCapacity,
		arg.CacheLen,
	)
	return err
}
