// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package queries

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, section_id, name, api_key_hash, base_config) VALUES 
(?, ?, ?, ?, ?)
RETURNING id
`

type CreateAgentParams struct {
	ID         string
	SectionID  string
	Name       string
	ApiKeyHash string
	BaseConfig string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.SectionID,
		arg.Name,
		arg.ApiKeyHash,
		arg.BaseConfig,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, version, section_id, name, api_key_hash, base_config, last_seen_at, created_at FROM agents WHERE id = ?
LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.SectionID,
		&i.Name,
		&i.ApiKeyHash,
		&i.BaseConfig,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentConfigurationBase = `-- name: GetAgentConfigurationBase :one
SELECT id, version, name, base_config FROM agents WHERE id = ?
LIMIT 1
`

type GetAgentConfigurationBaseRow struct {
	ID         string
	Version    int64
	Name       string
	BaseConfig string
}

func (q *Queries) GetAgentConfigurationBase(ctx context.Context, id string) (GetAgentConfigurationBaseRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentConfigurationBase, id)
	var i GetAgentConfigurationBaseRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.BaseConfig,
	)
	return i, err
}

const getAgentEndpoints = `-- name: GetAgentEndpoints :many
SELECT id, address, enabled FROM endpoints WHERE agent_id = ?
`

type GetAgentEndpointsRow struct {
	ID      string
	Address string
	Enabled sql.NullInt64
}

func (q *Queries) GetAgentEndpoints(ctx context.Context, agentID string) ([]GetAgentEndpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentEndpoints, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentEndpointsRow
	for rows.Next() {
		var i GetAgentEndpointsRow
		if err := rows.Scan(&i.ID, &i.Address, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentTags = `-- name: GetAgentTags :many
SELECT t.name FROM agent_tags at
JOIN tags t ON at.tag_id = t.id
WHERE at.agent_id = ?
`

func (q *Queries) GetAgentTags(ctx context.Context, agentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAgentTags, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEndpointTags = `-- name: GetEndpointTags :many
SELECT t.name FROM endpoint_tags et
JOIN tags t ON et.tag_id = t.id
WHERE et.endpoint_id = ?
`

func (q *Queries) GetEndpointTags(ctx context.Context, endpointID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEndpointTags, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, version, section_id, name, api_key_hash, base_config, last_seen_at, created_at FROM agents
ORDER BY id
LIMIT ? OFFSET ?
`

type ListAgentsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.SectionID,
			&i.Name,
			&i.ApiKeyHash,
			&i.BaseConfig,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsBySection = `-- name: ListAgentsBySection :many
SELECT id, version, section_id, name, api_key_hash, base_config, last_seen_at, created_at FROM agents
WHERE section_id = ?
ORDER BY id
LIMIT ? OFFSET ?
`

type ListAgentsBySectionParams struct {
	SectionID string
	Limit     int64
	Offset    int64
}

func (q *Queries) ListAgentsBySection(ctx context.Context, arg ListAgentsBySectionParams) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsBySection, arg.SectionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.SectionID,
			&i.Name,
			&i.ApiKeyHash,
			&i.BaseConfig,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET section_id = ?, name = ?, api_key_hash = ?, base_config = ?
WHERE id = ?
RETURNING id, version, section_id, name, api_key_hash, base_config, last_seen_at, created_at
`

type UpdateAgentParams struct {
	SectionID  string
	Name       string
	ApiKeyHash string
	BaseConfig string
	ID         string
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent,
		arg.SectionID,
		arg.Name,
		arg.ApiKeyHash,
		arg.BaseConfig,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.SectionID,
		&i.Name,
		&i.ApiKeyHash,
		&i.BaseConfig,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAgentConfiguration = `-- name: UpdateAgentConfiguration :exec
UPDATE agents
SET version = ?, base_config = ?
WHERE id = ?
`

type UpdateAgentConfigurationParams struct {
	Version    int64
	BaseConfig string
	ID         string
}

func (q *Queries) UpdateAgentConfiguration(ctx context.Context, arg UpdateAgentConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentConfiguration, arg.Version, arg.BaseConfig, arg.ID)
	return err
}
