// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package queries

import (
	"context"
)

const getEndpointByIDAndAgentID = `-- name: GetEndpointByIDAndAgentID :one
SELECT id FROM endpoints WHERE id = ? AND agent_id = ? LIMIT 1
`

type GetEndpointByIDAndAgentIDParams struct {
	ID      string
	AgentID string
}

func (q *Queries) GetEndpointByIDAndAgentID(ctx context.Context, arg GetEndpointByIDAndAgentIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getEndpointByIDAndAgentID, arg.ID, arg.AgentID)
	var id string
	err := row.Scan(&id)
	return id, err
}
