// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Agent struct {
	ID         string
	SectionID  string
	Name       string
	ApiKeyHash string
	BaseConfig string
	Version    int64
	LastSeenAt sql.NullString
	UpdatedAt  sql.NullString
	CreatedAt  sql.NullString
}

type AgentTag struct {
	AgentID string
	TagID   string
}

type Endpoint struct {
	ID        string
	AgentID   string
	Address   string
	Enabled   sql.NullInt64
	UpdatedAt sql.NullString
	CreatedAt sql.NullString
}

type EndpointTag struct {
	EndpointID string
	TagID      string
}

type Section struct {
	ID       string
	TenantID string
	Name     string
}

type Tag struct {
	ID        string
	SectionID string
	Name      string
	Scope     sql.NullString
}

type Tenant struct {
	ID        string
	Name      string
	CreatedAt sql.NullString
}
