// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth2_pending_states.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createPendingState = `-- name: CreatePendingState :exec
INSERT INTO oauth2_pending_states (
    id,
    state,
    provider,
    expires_at
) VALUES (?, ?, ?, ?)
`

type CreatePendingStateParams struct {
	ID        string
	State     string
	Provider  string
	ExpiresAt time.Time
}

func (q *Queries) CreatePendingState(ctx context.Context, arg CreatePendingStateParams) error {
	_, err := q.db.ExecContext(ctx, createPendingState,
		arg.ID,
		arg.State,
		arg.Provider,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredPendingStates = `-- name: DeleteExpiredPendingStates :exec
DELETE FROM oauth2_pending_states
WHERE expires_at <= datetime('now')
`

// Housekeeping: remove stale records older than their TTL.
func (q *Queries) DeleteExpiredPendingStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPendingStates)
	return err
}

const deletePendingState = `-- name: DeletePendingState :exec
DELETE FROM oauth2_pending_states
WHERE id = ?
`

// One-time use: delete after consuming at /token to prevent replay.
func (q *Queries) DeletePendingState(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePendingState, id)
	return err
}

const getPendingStateByAuthCode = `-- name: GetPendingStateByAuthCode :one
SELECT id, state, provider, auth_code, created_at, expires_at FROM oauth2_pending_states
WHERE auth_code = ?
  AND expires_at > datetime('now')
LIMIT 1
`

// Called at /token to retrieve provider; filters expired records.
func (q *Queries) GetPendingStateByAuthCode(ctx context.Context, authCode sql.NullString) (Oauth2PendingState, error) {
	row := q.db.QueryRowContext(ctx, getPendingStateByAuthCode, authCode)
	var i Oauth2PendingState
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Provider,
		&i.AuthCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setPendingStateAuthCode = `-- name: SetPendingStateAuthCode :exec
UPDATE oauth2_pending_states
SET auth_code = ?
WHERE state = ?
`

type SetPendingStateAuthCodeParams struct {
	AuthCode sql.NullString
	State    string
}

// Called at /callback when IdP returns the authorization code.
func (q *Queries) SetPendingStateAuthCode(ctx context.Context, arg SetPendingStateAuthCodeParams) error {
	_, err := q.db.ExecContext(ctx, setPendingStateAuthCode, arg.AuthCode, arg.State)
	return err
}
