// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id,
    token_hash,
    expires_at,
    absolute_expires_at,
    oauth2_provider,
    oauth2_access_token,
    oauth2_refresh_token,
    oauth2_token_expiry,
    oauth2_id_token,
    oauth2_scope,
    oauth2_token_type
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, token_hash, created_at, expires_at, absolute_expires_at, last_used_at, revoked, oauth2_provider, oauth2_access_token, oauth2_refresh_token, oauth2_token_expiry, oauth2_id_token, oauth2_scope, oauth2_token_type, oauth2_token_refresh_count, oauth2_token_refresh_last_at
`

type CreateSessionParams struct {
	ID                 string
	UserID             string
	TokenHash          string
	ExpiresAt          time.Time
	AbsoluteExpiresAt  time.Time
	Oauth2Provider     string
	Oauth2AccessToken  string
	Oauth2RefreshToken sql.NullString
	Oauth2TokenExpiry  sql.NullTime
	Oauth2IDToken      sql.NullString
	Oauth2Scope        sql.NullString
	Oauth2TokenType    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.Oauth2Provider,
		arg.Oauth2AccessToken,
		arg.Oauth2RefreshToken,
		arg.Oauth2TokenExpiry,
		arg.Oauth2IDToken,
		arg.Oauth2Scope,
		arg.Oauth2TokenType,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.Oauth2Provider,
		&i.Oauth2AccessToken,
		&i.Oauth2RefreshToken,
		&i.Oauth2TokenExpiry,
		&i.Oauth2IDToken,
		&i.Oauth2Scope,
		&i.Oauth2TokenType,
		&i.Oauth2TokenRefreshCount,
		&i.Oauth2TokenRefreshLastAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, created_at, expires_at, absolute_expires_at, last_used_at, revoked, oauth2_provider, oauth2_access_token, oauth2_refresh_token, oauth2_token_expiry, oauth2_id_token, oauth2_scope, oauth2_token_type, oauth2_token_refresh_count, oauth2_token_refresh_last_at FROM sessions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.Oauth2Provider,
		&i.Oauth2AccessToken,
		&i.Oauth2RefreshToken,
		&i.Oauth2TokenExpiry,
		&i.Oauth2IDToken,
		&i.Oauth2Scope,
		&i.Oauth2TokenType,
		&i.Oauth2TokenRefreshCount,
		&i.Oauth2TokenRefreshLastAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, created_at, expires_at, absolute_expires_at, last_used_at, revoked, oauth2_provider, oauth2_access_token, oauth2_refresh_token, oauth2_token_expiry, oauth2_id_token, oauth2_scope, oauth2_token_type, oauth2_token_refresh_count, oauth2_token_refresh_last_at FROM sessions
WHERE token_hash = ?
  AND revoked = 0
  AND expires_at > datetime('now')
  AND absolute_expires_at > datetime('now')
LIMIT 1
`

// Returns a valid, non-revoked, non-expired session by token hash.
// Does NOT filter on oauth2_token_expiry; middleware handles transparent IDP refresh.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastUsedAt,
		&i.Revoked,
		&i.Oauth2Provider,
		&i.Oauth2AccessToken,
		&i.Oauth2RefreshToken,
		&i.Oauth2TokenExpiry,
		&i.Oauth2IDToken,
		&i.Oauth2Scope,
		&i.Oauth2TokenType,
		&i.Oauth2TokenRefreshCount,
		&i.Oauth2TokenRefreshLastAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = 1
WHERE id = ?
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE sessions
SET last_used_at = datetime('now')
WHERE id = ?
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastUsed, id)
	return err
}

const updateSessionOAuth2Tokens = `-- name: UpdateSessionOAuth2Tokens :exec
UPDATE sessions
SET oauth2_access_token          = ?,
    oauth2_refresh_token         = ?,
    oauth2_token_expiry          = ?,
    oauth2_id_token              = ?,
    oauth2_token_refresh_count   = oauth2_token_refresh_count + 1,
    oauth2_token_refresh_last_at = datetime('now'),
    expires_at                   = min(datetime('now', '+7 days'), absolute_expires_at)
WHERE id = ?
`

type UpdateSessionOAuth2TokensParams struct {
	Oauth2AccessToken  string
	Oauth2RefreshToken sql.NullString
	Oauth2TokenExpiry  sql.NullTime
	Oauth2IDToken      sql.NullString
	ID                 string
}

// Updates IDP tokens after a transparent refresh.
// Slides expires_at forward by 7 days, capped at absolute_expires_at.
func (q *Queries) UpdateSessionOAuth2Tokens(ctx context.Context, arg UpdateSessionOAuth2TokensParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionOAuth2Tokens,
		arg.Oauth2AccessToken,
		arg.Oauth2RefreshToken,
		arg.Oauth2TokenExpiry,
		arg.Oauth2IDToken,
		arg.ID,
	)
	return err
}
